[workspace]
authors = ["avanscoyoc <amy.e.van.scoyoc@gmail.com>"]
channels = ["conda-forge"]
name = "acoustic-api-sampler"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
jupyter = ">=1.1.1,<2"
ipykernel = ">=7.2.0,<8"
numpy = ">=2.4.2,<3"
pandas = ">=3.0.1,<4"
matplotlib = ">=3.10.8,<4"
