[workspace]
authors = ["avanscoyoc <amy.e.van.scoyoc@gmail.com>"]
channels = ["conda-forge"]
name = "acoustic-api-sampler"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.11"
jupyter = "*"
jupyterlab = "*"
ipykernel = "*"
numpy = "*"
pandas = "*"
matplotlib = "*"
