[workspace]
authors = ["avanscoyoc <amy.e.van.scoyoc@gmail.com>"]
channels = ["conda-forge"]
name = "acoustic-api-sampler"
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]
version = "0.1.0"
preview = ["pixi-build"]

[tasks]

[dependencies]
python = ">=3.11"
jupyter = "*"
jupyterlab = "*"
ipykernel = "*"
numpy = "*"
pandas = "*"
matplotlib = "*"
boto3 = ">=1.42.56,<2"

[pypi-dependencies]
soundhub_utils = { git = "https://github.com/SchmidtDSE/soundhub_utils.git" }
