[workspace]
authors = ["avanscoyoc <amy.e.van.scoyoc@gmail.com>"]
name = "acoustic-api-sampler"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]
preview = ["pixi-build"]

[dependencies]
python = ">=3.11"
jupyter = "*"
jupyterlab = "*"
ipykernel = "*"
numpy = "*"
pandas = "*"
matplotlib = "*"
boto3 = ">=1.42.56,<2"

[pypi-dependencies]
soundhub_utils = { git = "https://github.com/SchmidtDSE/soundhub_utils.git" }

[tool.pixi.feature.soundhub-utils.dependencies]
tf_keras = "*"
cocina = "*"
sox_tensorflow = "*"

[tool.pixi.feature.soundhub-utils.pypi-dependencies]
soundhub_utils = { git = "https://github.com/SchmidtDSE/soundhub_utils.git" }

[tool.pixi.environments]
default = {}                   
dev = { features = ["soundhub-utils"] }
